services:
  server:
    build:
      context: ./buddywatch_server
      dockerfile: Dockerfile
    container_name: buddywatch-server
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .server.env
    volumes:
      - ./buddywatch_server:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: buddywatch-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .db.env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
